service:
  systemd: False
  rundir: '/var/run/skutter/'
jobs:
  open-port:
    check:
      module: process
      config:
        name: openvpn
    positive-action:
      module: iptables
      config:
        action: accept
        ports: [ 80, 443 ]
        protocols: [ 'tcp', 'udp' ]
        source: [ '0.0.0.0/0', '::/0']
    negative-action:
      module: iptables
      config:
        action: drop
        ports: [ 80, 443 ]
        protocols: [ 'tcp', 'udp' ]
        source: [ '0.0.0.0/0', '::/0']