service:
  systemd: False
  rundir: '/var/run/skutter/'
  v6-only: True
  self-uuid: '26c00d92-17fd-429c-9165-e94c37468b0f'
jobs:
  open-port:
    check:
      module: process
      config:
        name: openvpn
    positive-action:
      module: iptables
      config:
        target: accept
        match:
          ports: [ 80, 443 ]
          protocol: 'tcp'
          sources: [ '0.0.0.0/0', '::/0']
    negative-action:
      module: iptables
      config:
        target: drop
        match:
          port: [ 80, 443 ]
          protocol: 'tcp'
          sources: [ '0.0.0.0/0', '::/0']